[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
size = 12

[keyboard]
bindings = [
  { key = "V", mods = "Alt", action = "toggleViMode" },
]

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true
