[font]
# use JetBrainsMono NF/NFM/NFP
# pacman package: ttf-jetbrains-mono-nerd
# multiple styles are available, like 'Italic', 'Light', 'Bold'...
normal = { family = "JetBrainsMono NF", style = "Light" }
size = 14

# another font CodeNewRoman is a good choice
# pacman package: otf-codenewroman-nerd
# normal = { family = "CodeNewRoman Nerd Font", style = "Regular" }
# size = 16

[keyboard]
# for default alacritty bindings, check :Man alacritty-bindings
bindings = [
  { key = "V", mods = "Alt", action = "ToggleViMode" },
]

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true
