[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
size = 14

[keyboard]
# for default alacritty bindings, check :Man alacritty-bindings
bindings = [
  { key = "V", mods = "Alt", action = "ToggleViMode" },
]

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true
