gui:
  scrollHeight: 5 # how many lines you scroll by
  scrollPastBottom: false # enable scrolling past the bottom
promptToReturnFromSubprocess: false # display confirmation when subprocess terminates
customCommands:
  - key: '<c-g>'
    context: 'global'
    command: "nvim {{.SelectedFile.Name | quote }} -c 'GptCommit'"
    description: 'GPT generate commit message (via Neovim)'
    output: 'terminal'
